### ISSUE TITLE
Crash on non squared configuration

### ISSUE THREAD

**Issue by Neogene** [maximbilan/ios_crosswords_generator#2]
Hi, 

creating the crossword with a aXb with a!=b configuration Array2D crashes due to out of bounds into suggestCoord() method.

**Comment by maximbilan** [comment]
Hi,

Thanks. Yes, I see the app crashes. Sorry, I don't have time for resolving this right now. Maybe I will fix it in the nearest future.

Thanks.

**Comment by Neogene** [comment]
i fixed by myself, I simply switched if i'm not wrong the code into the array2d in the subscript function fyi

**Comment by maximbilan** [comment]
Fixed. Please use 0.3.3.
